In [1]:
import pandas as pd
import numpy as np

In [2]:
pddf = pd.read_csv('NewCricket.csv')

In [3]:
pdDF = pddf.copy()

In [4]:
pdDF.equals(pddf)

True

In [5]:
pdDF.info

<bound method DataFrame.info of      runs  ballsFaced  minutes  fours  sixes  strikeRate  isNotOut  \
0      15          14       24      0      1         107         0   
1      32          28       58      2      0         114         0   
2       8          12       15      1      0          66         0   
3      38          28       46      2      1         135         0   
4       0           6        8      0      0           0         0   
..    ...         ...      ...    ...    ...         ...       ...   
550    29          23       37      2      1         126         0   
551     4           8        9      0      0          50         0   
552     5           8       15      0      0          62         0   
553     0           0        4      0      0           0         0   
554     8          15       20      0      0          53         0   

     runningOver  Wickets  Runnings  
0            4.2        1        29  
1           11.1        3        84  
2            

In [6]:
pdDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555 entries, 0 to 554
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   runs         555 non-null    int64  
 1   ballsFaced   555 non-null    int64  
 2   minutes      555 non-null    int64  
 3   fours        555 non-null    int64  
 4   sixes        555 non-null    int64  
 5   strikeRate   555 non-null    int64  
 6   isNotOut     555 non-null    int64  
 7   runningOver  555 non-null    float64
 8   Wickets      555 non-null    int64  
 9   Runnings     555 non-null    int64  
dtypes: float64(1), int64(9)
memory usage: 43.5 KB


Using logistic regression to classify

creating targets

In [7]:
pdDF['Runnings'].median()

84.0

In [8]:
targets = np.where(pdDF['Runnings'] > pdDF['Runnings'].median(), 1, 0)

In [9]:
targets

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,

In [10]:
pdDF['RunPoints'] = targets

In [11]:
targets.sum()/targets.shape[0]

0.4990990990990991

In [12]:
pdDF = pdDF.drop(['Runnings', 'isNotOut'], axis = 1)
pdDF

runs  ballsFaced  minutes  fours  sixes  strikeRate  runningOver  \
0      15          14       24      0      1         107          4.2   
1      32          28       58      2      0         114         11.1   
2       8          12       15      1      0          66          7.1   
3      38          28       46      2      1         135         16.3   
4       0           6        8      0      0           0         12.2   
..    ...         ...      ...    ...    ...         ...          ...   
550    29          23       37      2      1         126         13.6   
551     4           8        9      0      0          50         12.3   
552     5           8       15      0      0          62         15.2   
553     0           0        4      0      0           0         14.2   
554     8          15       20      0      0          53         18.6   

     Wickets  RunPoints  
0          1          0  
1          3          0  
2          2          0  
3          5          1  
4          4          1  
..       ...        ...  
550        7          1  
551        6          0  
552        9          1  
553        8          1  
554       10          1  

[555 rows x 9 columns]

In [13]:
pdDF is pddf

False

In [14]:
pdDF.shape

(555, 9)

Selecting inputs

In [15]:
pdDF.iloc[ : , : -1]

runs  ballsFaced  minutes  fours  sixes  strikeRate  runningOver  Wickets
0      15          14       24      0      1         107          4.2        1
1      32          28       58      2      0         114         11.1        3
2       8          12       15      1      0          66          7.1        2
3      38          28       46      2      1         135         16.3        5
4       0           6        8      0      0           0         12.2        4
..    ...         ...      ...    ...    ...         ...          ...      ...
550    29          23       37      2      1         126         13.6        7
551     4           8        9      0      0          50         12.3        6
552     5           8       15      0      0          62         15.2        9
553     0           0        4      0      0           0         14.2        8
554     8          15       20      0      0          53         18.6       10

[555 rows x 8 columns]

In [16]:
unscaled_inputs = pdDF.iloc[ : , : -1]

In [17]:
unscaled_inputs.dropna(inplace=True)

Standardise the data

In [18]:
#from sklearn.preprocessing import StandardScaler
#running_scaler = StandardScaler()

In [19]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler:
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [20]:
unscaled_inputs.columns.values

array(['runs', 'ballsFaced', 'minutes', 'fours', 'sixes', 'strikeRate',
       'runningOver', 'Wickets'], dtype=object)

In [21]:
columns_to_omit = ['runs', 'ballsFaced', 'fours', 'sixes', 'strikeRate', 'Wickets']

In [22]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [23]:
running_scaler = CustomScaler(columns_to_scale)

In [24]:
running_scaler.fit(unscaled_inputs)

In [25]:
scaled_inputs = running_scaler.transform(unscaled_inputs)

In [26]:
scaled_inputs

runs  ballsFaced   minutes  fours  sixes  strikeRate  runningOver  \
0      15          14  0.080910      0      1         107    -1.178151   
1      32          28  1.841901      2      0         114    -0.016562   
2       8          12 -0.385234      1      0          66    -0.689947   
3      38          28  1.220375      2      1         135     0.858839   
4       0           6 -0.747791      0      0           0     0.168619   
..    ...         ...       ...    ...    ...         ...          ...   
550    29          23  0.754230      2      1         126     0.404304   
551     4           8 -0.695997      0      0          50     0.185454   
552     5           8 -0.385234      0      0          62     0.673658   
553     0           0 -0.954967      0      0           0     0.505312   
554     8          15 -0.126265      0      0          53     1.246035   

     Wickets  
0          1  
1          3  
2          2  
3          5  
4          4  
..       ...  
550        7  
551        6  
552        9  
553        8  
554       10  

[555 rows x 8 columns]

In [27]:
scaled_inputs.shape

(555, 8)

Training the model

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
train_test_split(scaled_inputs, targets)

[     runs  ballsFaced   minutes  fours  sixes  strikeRate  runningOver  \
 481    20          19 -0.126265      3      0         105    -1.127647   
 297    62          47  2.670603      5      2         131     0.690493   
 135    60          27  0.909612      7      3         222    -0.673112   
 437    13          12 -0.281647      2      0         108    -1.329662   
 7       4           8 -0.540616      0      0          50     1.363878   
 ..    ...         ...       ...    ...    ...         ...          ...   
 541    26          24  1.375757      2      0         108     0.404304   
 426    19          13 -0.229853      2      0         146     1.010351   
 198     0           3 -0.954967      0      0           0    -0.656277   
 262    14          16  0.029117      1      1          87    -1.144482   
 49     32          32  1.479344      2      1         100     0.000273   
 
      Wickets  
 481        2  
 297        4  
 135        1  
 437        1  
 7          8  
 .

In [30]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [31]:
print(x_train.shape, y_train.shape)

(444, 8) (444,)


In [32]:
print(x_test.shape, y_test.shape)

(111, 8) (111,)


In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [34]:
reg = LogisticRegression()

In [35]:
reg.fit(x_train, y_train)

C:\Users\ingobeni\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [36]:
reg.score(x_train, y_train)

0.9391891891891891

In [37]:
model_outputs = reg.predict(x_train)

In [38]:
model_outputs == y_train

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,

In [39]:
np.sum((model_outputs == y_train))

417

In [40]:
model_outputs.shape[0]

444

In [41]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.9391891891891891

exploring coefficient and interception

In [42]:
reg.intercept_

array([0.62496983])

In [43]:
reg.coef_

array([[ 1.43738670e-01, -1.68107059e-01,  2.17446483e-01,
        -1.71280787e-01, -3.35636074e-01,  3.86396277e-04,
         4.80877833e+00, -1.59132655e-01]])

In [44]:
unscaled_inputs.columns.values

array(['runs', 'ballsFaced', 'minutes', 'fours', 'sixes', 'strikeRate',
       'runningOver', 'Wickets'], dtype=object)

In [45]:
feature_name = unscaled_inputs.columns.values

creating summary table

In [46]:
summary_table = pd.DataFrame(columns = ['feature_name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

feature_name  Coefficient
0    Intercept     0.624970
1         runs     0.143739
2   ballsFaced    -0.168107
3      minutes     0.217446
4        fours    -0.171281
5        sixes    -0.335636
6   strikeRate     0.000386
7  runningOver     4.808778
8      Wickets    -0.159133

In [47]:
summary_table['Odds_ratios'] = np.exp(summary_table.Coefficient)

In [48]:
summary_table

feature_name  Coefficient  Odds_ratios
0    Intercept     0.624970     1.868190
1         runs     0.143739     1.154582
2   ballsFaced    -0.168107     0.845263
3      minutes     0.217446     1.242899
4        fours    -0.171281     0.842585
5        sixes    -0.335636     0.714883
6   strikeRate     0.000386     1.000386
7  runningOver     4.808778   122.581771
8      Wickets    -0.159133     0.852883

In [49]:
summary_table.sort_values('Odds_ratios', ascending = False)

feature_name  Coefficient  Odds_ratios
7  runningOver     4.808778   122.581771
0    Intercept     0.624970     1.868190
3      minutes     0.217446     1.242899
1         runs     0.143739     1.154582
6   strikeRate     0.000386     1.000386
8      Wickets    -0.159133     0.852883
2   ballsFaced    -0.168107     0.845263
4        fours    -0.171281     0.842585
5        sixes    -0.335636     0.714883

Testing

In [50]:
reg.score(x_test, y_test)

0.954954954954955

In [53]:
predict_probability = reg.predict_proba(x_test)
predict_probability

array([[5.16185986e-02, 9.48381401e-01],
       [9.96789072e-01, 3.21092774e-03],
       [3.22609700e-03, 9.96773903e-01],
       [8.75541631e-01, 1.24458369e-01],
       [2.03767834e-01, 7.96232166e-01],
       [9.99661997e-01, 3.38002921e-04],
       [4.26459762e-03, 9.95735402e-01],
       [5.16917588e-01, 4.83082412e-01],
       [2.15301420e-01, 7.84698580e-01],
       [9.99160401e-01, 8.39599263e-04],
       [9.90936266e-01, 9.06373375e-03],
       [9.94348226e-01, 5.65177373e-03],
       [9.99714463e-01, 2.85536782e-04],
       [9.99610580e-01, 3.89420305e-04],
       [9.99708932e-01, 2.91067668e-04],
       [1.73747588e-02, 9.82625241e-01],
       [1.26961840e-02, 9.87303816e-01],
       [9.98359911e-01, 1.64008888e-03],
       [9.99749042e-01, 2.50957602e-04],
       [3.54632580e-03, 9.96453674e-01],
       [3.95008186e-01, 6.04991814e-01],
       [9.41439344e-01, 5.85606560e-02],
       [3.73242858e-02, 9.62675714e-01],
       [1.84464607e-03, 9.98155354e-01],
       [1.538660

In [54]:
predict_probability.shape

(111, 2)

In [55]:
predict_probability[ : , 1]

array([9.48381401e-01, 3.21092774e-03, 9.96773903e-01, 1.24458369e-01,
       7.96232166e-01, 3.38002921e-04, 9.95735402e-01, 4.83082412e-01,
       7.84698580e-01, 8.39599263e-04, 9.06373375e-03, 5.65177373e-03,
       2.85536782e-04, 3.89420305e-04, 2.91067668e-04, 9.82625241e-01,
       9.87303816e-01, 1.64008888e-03, 2.50957602e-04, 9.96453674e-01,
       6.04991814e-01, 5.85606560e-02, 9.62675714e-01, 9.98155354e-01,
       8.46133976e-01, 8.34125777e-01, 7.55798874e-01, 7.95025568e-01,
       9.92850077e-01, 9.67262662e-01, 5.16534823e-01, 1.04518747e-03,
       1.78880653e-04, 2.20671183e-03, 3.29571010e-04, 6.26115005e-01,
       7.27031286e-01, 9.91842088e-01, 9.74590080e-01, 8.81785252e-03,
       8.18786140e-04, 7.70049515e-01, 8.48687645e-01, 8.33475341e-01,
       4.60912447e-01, 7.84435079e-01, 9.79778310e-01, 4.03204714e-01,
       1.00451884e-02, 9.33011947e-01, 2.13673551e-03, 1.24271359e-04,
       2.63591144e-03, 1.32566917e-04, 1.42652763e-03, 9.96251418e-01,
      

Saving the model

In [56]:
import pickle

In [57]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [60]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(running_scaler, file)

LinkedIn
Ismael (Ishmael T.) Ngobeni